# Generated by Django 4.0.6 on 2022-07-19 15:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
    ]
